# Generated by Django 3.1.4 on 2020-12-31 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='加工廠商',
            fields=[
                ('加工廠商ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('加工廠商名稱', models.CharField(max_length=20)),
                ('地址', models.CharField(max_length=50)),
                ('電話', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['加工廠商ID'],
            },
        ),
        migrations.CreateModel(
            name='加工產品',
            fields=[
                ('加工批號', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('加工產品名稱', models.CharField(max_length=20)),
                ('產量', models.FloatField()),
                ('製造日期', models.DateField()),
                ('加工廠商ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_query.加工廠商')),
            ],
            options={
                'ordering': ['加工批號'],
            },
        ),
        migrations.CreateModel(
            name='生產者',
            fields=[
                ('生產者ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('名稱', models.CharField(max_length=20)),
                ('電話', models.CharField(max_length=20)),
                ('地址', models.CharField(max_length=50)),
                ('農產品經營業者', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['生產者ID'],
            },
        ),
        migrations.CreateModel(
            name='產銷履歷商品',
            fields=[
                ('追溯號碼', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('產品名稱', models.CharField(max_length=50)),
                ('產地', models.CharField(max_length=20)),
                ('包裝日期', models.DateField()),
                ('驗證機構', models.CharField(max_length=100)),
                ('產銷作業基準', models.CharField(max_length=20, null=True)),
                ('生產者ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_query.生產者')),
            ],
            options={
                'ordering': ['追溯號碼'],
            },
        ),
        migrations.CreateModel(
            name='銷售通路',
            fields=[
                ('銷售通路ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('銷售通路名稱', models.CharField(max_length=20)),
                ('電話', models.CharField(max_length=20)),
                ('地址', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['銷售通路ID'],
            },
        ),
        migrations.CreateModel(
            name='餐廳',
            fields=[
                ('餐廳ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('名稱', models.CharField(max_length=30)),
                ('電話', models.CharField(max_length=15)),
                ('地址', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['餐廳ID'],
            },
        ),
        migrations.CreateModel(
            name='餐廳_產銷履歷',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('重量', models.FloatField()),
                ('訂貨日期', models.DateField()),
                ('追溯號碼', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_query.產銷履歷商品')),
                ('餐廳ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_query.餐廳')),
            ],
            options={
                'ordering': ['餐廳ID', '追溯號碼'],
            },
        ),
        migrations.CreateModel(
            name='餐廳_加工產品',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('重量', models.FloatField()),
                ('訂貨日期', models.DateField()),
                ('加工批號', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_query.加工產品')),
                ('餐廳ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_query.餐廳')),
            ],
            options={
                'ordering': ['餐廳ID', '加工批號'],
            },
        ),
        migrations.CreateModel(
            name='產銷履歷商品_銷售通路',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('重量', models.FloatField()),
                ('訂貨日期', models.DateField()),
                ('追溯號碼', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_query.產銷履歷商品')),
                ('銷售通路ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_query.銷售通路')),
            ],
            options={
                'ordering': ['銷售通路ID', '追溯號碼'],
            },
        ),
        migrations.CreateModel(
            name='加工產品_銷售通路',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('重量', models.FloatField()),
                ('訂貨日期', models.DateField()),
                ('加工批號', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_query.加工產品')),
                ('銷售通路ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_query.銷售通路')),
            ],
            options={
                'ordering': ['銷售通路ID', '加工批號'],
            },
        ),
        migrations.CreateModel(
            name='加工產品_原料',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('加工批號', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_query.加工產品')),
                ('追溯號碼', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_query.產銷履歷商品')),
            ],
            options={
                'ordering': ['加工批號', '追溯號碼'],
            },
        ),
    ]
