# Generated by Django 3.1.4 on 2021-01-16 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_query', '0004_auto_20210103_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='餐廳',
            old_name='加工',
            new_name='加工產品',
        ),
        migrations.RenameField(
            model_name='餐廳',
            old_name='產銷',
            new_name='產銷履歷商品',
        ),
    ]
